### PR TITLE
Merge Request from Feature/restaurant pages to Develop branch

### PR DESCRIPTION
**Pull request by temesghentekeste**
Dear TSE,
Greetings! I have started the project by creating a repo called restaurant-js. Initially, I have set up Webpack, ESLint, StyleLint, and used git-flow as my git workflow. All the logic is put inside a feature branch called restaurant-pages. Inside the project, most of the codes are written in ES6 and I have modularized the codebase to achieve separation of concerns. 

Looking forward to hearing your constructive feedback, I kindly request a pull request before I merge my feature branch to the develop branch.

Temesghen T.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

the project looks great and you've met almost all requirements, the website works as expected, but `webpack` is not configured the way it's meant to be (your way looks absolutely fine, but we need to follow the guidelines here even though it does the same thing) 

- [ ] you need to move the `template.html` to dist, and name it `index.html`, from there you should link `main.js` (that would be in the same folder),
- [ ] `main.js` would be created when you do `npm run build` (right now it adds random numbers in the middle) 

again, I understand that your way works, but as you can see in [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/dist_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page) that you're supposed to do it this way

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by temesghentekeste** [comment]
Thanks for your review. I totally understand what you are suggesting; however, what is mentioned in the Odin Project is the basic configuration and it is always recommended to have a template in order to generate the HTML file and to bust the cache it is good to have  CSS  and JS files generated with some content hashes. So, I kindly request my project to be approved as it stands.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hi @temesghentekeste :hand: 
Awesome job on your project. It looks really great. 
However, we need to make the change requested in the last review. The reason for this is because Microverse uses the same requirements as the Odin page for this project. This way we TSEs must use these requirements when reviewing this project.

- [ ] It seems that the .eslintrc file is different from the one provided by Microvese. We need to use this version [instead](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json).

- On /dist folder we should have:

- [ ] It has a main file named index.html
- [ ] It has a main.js file that is built by webpack
- [ ] The index.html links the main.js file
Screenshot from 2021-01-20 18-07-20

Happy coding :computer: 
**Sergio Torres**

**Comment by temesghentekeste** [comment]
Greetings! I have addressed the issues. Kindly request a code review. Thanks in advance.

**Review by rOluochKe — APPROVED** [review]
### Hello @temesghentekeste 
### Good job in making the changes, the project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Comment by temesghentekeste** [comment]
Thanks @rOluochKe.

**Pull request merged**
